# Знакомство с данными

Три файла задания: `train.parquet` — пары «запрос → выбранное объявление», `benchmark_queries.parquet` — запросы без разметки, `benchmark_items.parquet` — корпус, из которого нужно выбирать кандидатов.

Хочу понять, что считать запросом, насколько train похож на бенчмарк и какие поля пригодятся для поиска.

In [ ]:
from pathlib import Path

import pandas as pd

DATA_DIR = Path("../dataset")

In [ ]:
train = pd.read_parquet(DATA_DIR / "train.parquet")
queries = pd.read_parquet(DATA_DIR / "benchmark_queries.parquet")
items = pd.read_parquet(DATA_DIR / "benchmark_items.parquet")

print("Размеры:")
print("train:", train.shape)
print("queries:", queries.shape)
print("items:", items.shape)

Размеры:
train: (497673, 19)
queries: (2452, 6)
items: (189212, 14)

In [ ]:
train.head()

,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category,item_title_raw,item_rating_reviews_count,item_rating,item_price,item_microcat_id,item_longitude,item_location_id,item_latitude,item_is_phone_hidden,item_is_message_forbidden,item_infm_params_text,item_id,item_description_raw,item_category_id
0,скупка телевизоров,652430,0,,114,Скупка б/у техники,91.0,4.989011,1.000000000000000,2303374,39.712818145751953,652430,54.629230499267578,True,False,Вид услуги Место оказания услуг Первомайский п...,e8b685dffe1a408e,Скупаю практически любую современную новую и б...,114
1,автоподбор,640860,0,Рейтинг пользователя 4 звезды и выше,114,Автоподбор Разовый осмотр автомобиля,462.0,4.982684,3500.000000000000000,2303374,44.051009999999998,640860,56.273389999999999,False,False,Вид услуги Место оказания услуг Нижний Новгоро...,92e1b0446f827b59,🚗 Автоподбор и выездная диагностика автомобиля...,114
2,баня на дровах,653240,0,"Онлайн-запись Тип услуги СПА-услуги, массаж Ви...",114,"Баня на дровах ""Прованс"" на Цветочной",NaN,NaN,1600.000000000000000,86469,30.128784180000000,653240,59.783687590000000,False,False,"Вид услуги Красота, здоровье Место оказания ус...",624846856ce81d69,В ритме современной жизни так сложно найти мо...,114
3,изготовление госномера на авто,634670,0,"Вид услуги Оборудование, производство",114,"Изготовление дубликатов авто номеров, гос номеров",14.0,4.714286,1700.000000000000000,2303428,40.537841000000000,633570,45.424875000000000,False,False,"Вид услуги Оборудование, производство Тип услу...",45b8628b9c6e7b85,Изготовим дубликат номера по утере или износу ...,114
4,укладка плитки,658430,0,Тип услуги Ремонт квартир и домов под ключ Вид...,114,Ремонт и отделка квартир под ключ,1.0,5.000000,1000.000000000000000,44725,69.496444699999998,658430,56.105983729999998,False,False,Вид услуги Ремонт и отделка Тип услуги Ремонт ...,c95a4a7daf2a967f,отделочные работы любой сложности.,114

In [ ]:
queries.head()

,query_id,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category
0,70DfDUpwjxB4lzFd,перевозки владикавказ тбилиси,649820,0,,114
1,JTrdTaZJvSiLPkXj,обзвон по базе,107620,0,Вид услуги Деловые услуги,114
2,LZCZNoVG4AFUkVRJ,липоредукция подбородка,637640,0,"Вид услуги Красота, здоровье",114
3,660ac9QVtXkRxZC3,подъемник 4 х стоечный,662810,0,,114
4,YgHcM9MVbxKnxD1e,монтаж видеодомофонов,642790,0,,114

In [ ]:
items.head()

,item_title_raw,item_rating_reviews_count,item_rating,item_price,item_microcat_id,item_longitude,item_location_id,item_latitude,item_is_phone_hidden,item_is_message_forbidden,item_infm_params_text,item_id,item_description_raw,item_category_id
0,Ремонт/выкуп компьют. и ноутбуков с выездом на...,57.0,5.0,500.000000000000000,2097573,42.047193961004901,631060,44.228180450924000,False,False,Вид услуги Компьютерная помощь Место оказания ...,111eb8b979577d79,"Выезд на дом в любое время, вплоть до 23:00\n\...",114
1,Обучение ребенка чтению,7.0,5.0,900.000000000000000,86453,49.627391820000000,631870,58.627609249999999,False,False,"Вид услуги Обучение, курсы Место оказания услу...",75fc8e10f5a66fc4,"Дорогие родители и маленькие книголюбы! \n\nЯ,...",114
2,Афрокудри 5+,14.0,5.0,1000.000000000000000,86467,40.936892000000000,628500,56.990307000000001,True,False,"Вид услуги Красота, здоровье Место оказания ус...",3f6ae81704565b9c,ВНИМАНИЕ Укладка !!!! 🥳\n\nАФРОкудри отличный ...,114
3,Монтаж малых архитектурных форм,2.0,5.0,5000.000000000000000,2058739,37.576183000000000,637640,55.662734999999998,False,False,Вид услуги Строительство Место оказания услуг ...,0618dec37a59a21a,Оказываем все виды услуг по сборке и монтажу и...,114
4,Репетитор по истории 10 класс ЕГЭ,19.0,5.0,1500.000000000000000,86456,44.750473999999997,624850,48.786008000000002,False,False,"Вид услуги Обучение, курсы Место оказания услу...",13da2c81574677ed,🚀 Сдай ЕГЭ по истории на 80+ за 6 месяцев!\n\n...,114

Пропусков почти нет: рейтинг и число отзывов есть не у всех объявлений, у четырёх строк train нет координат.

In [ ]:
print(train.isna().sum())
print(queries.isna().sum())
print(items.isna().sum())

search_query                     0
search_location_id               0
search_is_delivery_search        0
search_infm_params_text          0
search_category                  0
item_title_raw                   0
item_rating_reviews_count    19211
item_rating                  28232
item_price                       0
item_microcat_id                 0
item_longitude                   4
item_location_id                 0
item_latitude                    4
item_is_phone_hidden             0
item_is_message_forbidden        0
item_infm_params_text            0
item_id                          0
item_description_raw             0
item_category_id                 0
dtype: int64
query_id                     0
search_query                 0
search_location_id           0
search_is_delivery_search    0
search_infm_params_text      0
search_category              0
dtype: int64
item_title_raw                   0
item_rating_reviews_count    11615
item_rating                  17631
item_price                       0
item_microcat_id                 0
item_longitude                   1
item_location_id                 0
item_latitude                    1
item_is_phone_hidden             0
item_is_message_forbidden        0
item_infm_params_text            0
item_id                          0
item_description_raw            35
item_category_id                 0
dtype: int64

In [ ]:
print(train['item_price'].apply(type).value_counts())
print(train['item_price'].head(10).tolist())

print(train['item_latitude'].apply(type).value_counts())
print(train['item_latitude'].head(10).tolist())

item_price
<class 'decimal.Decimal'>    497673
Name: count, dtype: int64
[Decimal('1.000000000000000'), Decimal('3500.000000000000000'), Decimal('1600.000000000000000'), Decimal('1700.000000000000000'), Decimal('1000.000000000000000'), Decimal('1500.000000000000000'), Decimal('700.000000000000000'), Decimal('4000.000000000000000'), Decimal('100000.000000000000000'), Decimal('1000.000000000000000')]
item_latitude
<class 'decimal.Decimal'>    497669
<class 'NoneType'>                4
Name: count, dtype: int64
[Decimal('54.629230499267578'), Decimal('56.273389999999999'), Decimal('59.783687590000000'), Decimal('45.424875000000000'), Decimal('56.105983729999998'), Decimal('55.746436000000003'), Decimal('55.742385859999999'), Decimal('55.918952939999997'), Decimal('55.174182999999999'), Decimal('48.490543369999997')]

## Пересечение train и корпуса бенчмарка

Если бы объявления бенчмарка встречались в train, можно было бы опираться на историю кликов по конкретным `item_id`.

In [ ]:
train_item_ids = set(train["item_id"].dropna().unique())
corpus_item_ids = set(items["item_id"].dropna().unique())

common_item_ids = train_item_ids & corpus_item_ids

print("Уникальных item_id в train:", len(train_item_ids))
print("Уникальных item_id в items:", len(corpus_item_ids))
print("Пересечение:", len(common_item_ids))

Уникальных item_id в train: 344825
Уникальных item_id в items: 189212
Пересечение: 18142

Общих объявлений 18 142 из 189 212, около 10%. Искать нужно по содержанию — тексту, категории, локации.

## Уникальные

74.5 тыс. уникальных текстов

In [ ]:
print("Уникальных search_query (по тексту):", train['search_query'].nunique())
print("Строк train:", len(train))
print("Среднее число объявлений на уникальный текст запроса:",
      len(train) / train['search_query'].nunique())

print(train.groupby('search_query').size().describe())

Уникальных search_query (по тексту): 74529
Строк train: 497673
Среднее число объявлений на уникальный текст запроса: 6.677575172080666
count    74529.000000
mean         6.677575
std         64.865220
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max       6540.000000
dtype: float64

In [ ]:
print(train['search_query'].value_counts().head(15))

search_query
маникюр                    6540
массаж                     5702
наращивание ресниц         5395
установка кондиционеров    4573
педикюр                    3436
сантехник                  3405
вывоз мусора               3278
эвакуатор                  3263
электрик                   3158
автоэлектрик               2790
покос травы                2477
вспашка земли              2315
манипулятор                2120
грузоперевозки газель      2034
натяжные потолки           2004
Name: count, dtype: int64

## Дубликаты

Сначала дубли пар «текст запроса — объявление».

In [ ]:
print("Дублирующихся пар (search_query, item_id):",
      train.duplicated(subset=['search_query', 'item_id']).sum())

Дублирующихся пар (search_query, item_id): 52412

Часть из них — один и тот же текст в разных городах или с разными фильтрами, то есть разные запросы. Настоящий дубль — совпадение всех полей `search_*` и `item_id`.

In [ ]:
search_cols = ['search_query', 'search_location_id', 'search_is_delivery_search',
               'search_infm_params_text', 'search_category']

print("Уникальных комбинаций search_* полей:", train[search_cols].drop_duplicates().shape[0])

dup_mask = train.duplicated(subset=['search_query', 'item_id'], keep=False)
dup_rows = train[dup_mask].sort_values('search_query')

check = dup_rows.groupby(['search_query', 'item_id'])[search_cols[1:]].nunique()
print(check.describe())
print(check[(check > 1).any(axis=1)].head(10))

full_dup = train.duplicated(subset=search_cols + ['item_id'], keep=False)
print("Дублей по ВСЕМ search_* полям + item_id:", full_dup.sum())

Уникальных комбинаций search_* полей: 354463
       search_location_id  search_is_delivery_search  search_infm_params_text  \
count        32006.000000                    32006.0             32006.000000
mean             1.245641                        1.0                 1.536493
std              0.454345                        0.0                 0.574054
min              1.000000                        1.0                 1.000000
25%              1.000000                        1.0                 1.000000
50%              1.000000                        1.0                 2.000000
75%              1.000000                        1.0                 2.000000
max              6.000000                        1.0                 6.000000

       search_category
count     32006.000000
mean          1.000031
std           0.005590
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           2.000000
                                   search_location_id  \
search_query     item_id
115-фз           5d26f0c3faecce23                   2
3 д печать       832040c634c1f5a3                   2
3d моделирование 62a7a422045c3a5a                   2
                 9fc960730150b594                   2
                 a9cd2f7c0cedd388                   2
                 d6eed55de95ddec8                   2
3d печать        033f3dab47a17581                   1
                 0526226e3911d58f                   1
                 319ab686b38231da                   1
                 3f502c9092c7ba58                   1

                                   search_is_delivery_search  \
search_query     item_id
115-фз           5d26f0c3faecce23                          1
3 д печать       832040c634c1f5a3                          1
3d моделирование 62a7a422045c3a5a                          1
                 9fc960730150b594                          1
                 a9cd2f7c0cedd388                          1
                 d6eed55de95ddec8                          1
3d печать        033f3dab47a17581                          1
                 0526226e3911d58f                          1
                 319ab686b38231da                          1
                 3f502c9092c7ba58                          1

                                   search_infm_params_text  search_category
search_query     item_id
115-фз           5d26f0c3faecce23                        1                1
3 д печать       832040c634c1f5a3                        1                1
3d моделирование 62a7a422045c3a5a                        2                1
                 9fc960730150b594                        2                1
                 a9cd2f7c0cedd388                        1                1
                 d6eed55de95ddec8                        2                1
3d печать        033f3dab47a17581                        2                1
                 0526226e3911d58f                        2                1
                 319ab686b38231da                        2                1
                 3f502c9092c7ba58                        2                1
Дублей по ВСЕМ search_* полям + item_id: 48533

Полные дубли не идут подряд и стоят на разных местах в файле — похоже на одинаковые клики разных пользователей, а не на технический артефакт. Для валидации их можно удалить.

In [ ]:
search_cols = ['search_query', 'search_location_id', 'search_is_delivery_search',
               'search_infm_params_text', 'search_category']
full_key = search_cols + ['item_id']

full_dup_mask = train.duplicated(subset=full_key, keep=False)
full_dups = train[full_dup_mask].sort_values(full_key)

print("Всего строк в полных дублях (все вхождения):", len(full_dups))
print("Из них уникальных комбинаций (сколько 'групп' дублей):",
      full_dups.drop_duplicates(subset=full_key).shape[0])

dup_counts = full_dups.groupby(full_key).size().sort_values(ascending=False)
print(dup_counts.describe())
print(dup_counts.head(10))

top_dup_key = dup_counts.index[0]
example = train[
    (train['search_query'] == top_dup_key[0]) &
    (train['search_location_id'] == top_dup_key[1]) &
    (train['search_is_delivery_search'] == top_dup_key[2]) &
    (train['search_infm_params_text'] == top_dup_key[3]) &
    (train['search_category'] == top_dup_key[4]) &
    (train['item_id'] == top_dup_key[5])
]
print(example)

pairs_count2 = dup_counts[dup_counts == 2].index[:5]
for key in pairs_count2:
    subset = train[
        (train['search_query'] == key[0]) &
        (train['search_location_id'] == key[1]) &
        (train['search_is_delivery_search'] == key[2]) &
        (train['search_infm_params_text'] == key[3]) &
        (train['search_category'] == key[4]) &
        (train['item_id'] == key[5])
    ]
    print(subset[['search_query', 'item_id'] + [c for c in subset.columns if c not in full_key]])
    print('---')

Всего строк в полных дублях (все вхождения): 48533
Из них уникальных комбинаций (сколько 'групп' дублей): 17914
count    17914.000000
mean         2.709222
std          3.687829
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max        171.000000
dtype: float64
search_query                                    search_location_id  search_is_delivery_search  search_infm_params_text                                   search_category  item_id
увеличение губ                                  653240              0                          Тип услуги Косметология Вид услуги Красота, здоровье      114              391037f10a20ee24    171
остекление лоджии и балконов - ремонт под ключ  653240              0                          Тип услуги Окна и балконы Вид услуги Ремонт и отделка     114              4be48741454a11dc    126
остекление лоджий по ключ                       653240              0                          Тип услуги Окна и балконы Вид услуги Ремонт и отделка     114              196d654750fa4944    117
интерьерная и архитектурная съемка              650400              0                          Вид услуги Фото- и видеосъёмка                            114              198eb6ac3f0dce86     95
предметная съемка для бизнеса                   650400              0                          Вид услуги Фото- и видеосъёмка                            114              8e223b1181386346     92
деловая и корпоративная фотосъемка              650400              0                          Вид услуги Фото- и видеосъёмка                            114              ad0b5c32404b1471     91
дизайнер интерьера. дизайн проект под ключ 3d   653240              0                          Тип услуги Дизайн интерьеров Вид услуги Ремонт и отделка  114              6075f787fa6453ba     77
зарабатывайте на банкротных торгах              653240              0                                                                                    114              90e5431121feda04     74
вскрытие замков                                 646600              0                          Тип услуги Вид услуги Ремонт и отделка                    114              be94ed17c23c5ed2     74
                                                                                                                                                                          1d507201b6a68916     74
dtype: int64
          search_query  search_location_id  search_is_delivery_search  \
4930    увеличение губ              653240                          0
5533    увеличение губ              653240                          0
5996    увеличение губ              653240                          0
9407    увеличение губ              653240                          0
13660   увеличение губ              653240                          0
...                ...                 ...                        ...
480687  увеличение губ              653240                          0
482630  увеличение губ              653240                          0
491646  увеличение губ              653240                          0
493492  увеличение губ              653240                          0
494582  увеличение губ              653240                          0

                                  search_infm_params_text  search_category  \
4930    Тип услуги Косметология Вид услуги Красота, зд...              114
5533    Тип услуги Косметология Вид услуги Красота, зд...              114
5996    Тип услуги Косметология Вид услуги Красота, зд...              114
9407    Тип услуги Косметология Вид услуги Красота, зд...              114
13660   Тип услуги Косметология Вид услуги Красота, зд...              114
...                                                   ...              ...
480687  Тип услуги Косметология Вид услуги Красота, зд...              114
482630  Тип услуги Косметология Вид услуги Красота, зд...              114
491646  Тип услуги Косметология Вид услуги Красота, зд...              114
493492  Тип услуги Косметология Вид услуги Красота, зд...              114
494582  Тип услуги Косметология Вид услуги Красота, зд...              114

                                           item_title_raw  \
4930    Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
5533    Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
5996    Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
9407    Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
13660   Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
...                                                   ...
480687  Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
482630  Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
491646  Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
493492  Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки
494582  Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки

        item_rating_reviews_count  item_rating            item_price  \
4930                        123.0     4.934959  6990.000000000000000
5533                        123.0     4.934959  6990.000000000000000
5996                        123.0     4.934959  6990.000000000000000
9407                        123.0     4.934959  6990.000000000000000
13660                       123.0     4.934959  6990.000000000000000
...                           ...          ...                   ...
480687                      123.0     4.934959  6990.000000000000000
482630                      123.0     4.934959  6990.000000000000000
491646                      123.0     4.934959  6990.000000000000000
493492                      123.0     4.934959  6990.000000000000000
494582                      123.0     4.934959  6990.000000000000000

        item_microcat_id      item_longitude  item_location_id  \
4930             2096640  30.318330992856225            653240
5533             2096640  30.318330992856225            653240
5996             2096640  30.318330992856225            653240
9407             2096640  30.318330992856225            653240
13660            2096640  30.318330992856225            653240
...                  ...                 ...               ...
480687           2096640  30.318330992856225            653240
482630           2096640  30.318330992856225            653240
491646           2096640  30.318330992856225            653240
493492           2096640  30.318330992856225            653240
494582           2096640  30.318330992856225            653240

             item_latitude  item_is_phone_hidden  item_is_message_forbidden  \
4930    60.041219693112787                 False                      False
5533    60.041219693112787                 False                      False
5996    60.041219693112787                 False                      False
9407    60.041219693112787                 False                      False
13660   60.041219693112787                 False                      False
...                    ...                   ...                        ...
480687  60.041219693112787                 False                      False
482630  60.041219693112787                 False                      False
491646  60.041219693112787                 False                      False
493492  60.041219693112787                 False                      False
494582  60.041219693112787                 False                      False

                                    item_infm_params_text           item_id  \
4930    Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
5533    Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
5996    Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
9407    Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
13660   Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
...                                                   ...               ...
480687  Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
482630  Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
491646  Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
493492  Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24
494582  Вид услуги Красота, здоровье Место оказания ус...  391037f10a20ee24

                                     item_description_raw  item_category_id
4930    Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
5533    Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
5996    Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
9407    Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
13660   Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
...                                                   ...               ...
480687  Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
482630  Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
491646  Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
493492  Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114
494582  Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...               114

[171 rows x 19 columns]
       search_query           item_id  \
24913     видеограф  6d04a93f1988297f
176529    видеограф  6d04a93f1988297f

                                    item_title_raw  item_rating_reviews_count  \
24913   Свадебная видеосъемка. Свадебный видеограф                       44.0
176529  Свадебная видеосъемка. Свадебный видеограф                       44.0

        item_rating          item_price  item_microcat_id      item_longitude  \
24913      4.909091  -1.000000000000000           2301875  40.973013999999999
176529     4.909091  -1.000000000000000           2301875  40.973013999999999

        item_location_id       item_latitude  item_is_phone_hidden  \
24913             628500  56.999799000000003                  True
176529            628500  56.999799000000003                  True

        item_is_message_forbidden  \
24913                       False
176529                      False

                                    item_infm_params_text  \
24913   Вид услуги Фото- и видеосъёмка Место оказания ...
176529  Вид услуги Фото- и видеосъёмка Место оказания ...

                                     item_description_raw  item_category_id
24913   ❤️ СВАДЕБНЫЙ ВИДЕОГРАФ (Стас и Ника): Сохраним...               114
176529  ❤️ СВАДЕБНЫЙ ВИДЕОГРАФ (Стас и Ника): Сохраним...               114
---

       search_query           item_id                  item_title_raw  \
160440    видеограф  c28a340b403d9a0e  Свадебный видеограф Красноярск
457363    видеограф  c28a340b403d9a0e  Свадебный видеограф Красноярск

        item_rating_reviews_count  item_rating            item_price  \
160440                        2.0          5.0  1000.000000000000000
457363                        2.0          5.0  1000.000000000000000

        item_microcat_id      item_longitude  item_location_id  \
160440           2301875  92.868409000000000            635320
457363           2301875  92.868409000000000            635320

             item_latitude  item_is_phone_hidden  item_is_message_forbidden  \
160440  56.008645999999999                 False                      False
457363  56.008645999999999                 False                      False

                                    item_infm_params_text  \
160440  Вид услуги Фото- и видеосъёмка Место оказания ...
457363  Вид услуги Фото- и видеосъёмка Место оказания ...

                                     item_description_raw  item_category_id
160440  Календарь быстро заполняется — успей заброниро...               114
457363  Календарь быстро заполняется — успей заброниро...               114
---
       search_query           item_id                       item_title_raw  \
146790    видеограф  e52a1dcbfc6a9e5e  4k UltraHD Фотограф и Видеооператор
192095    видеограф  e52a1dcbfc6a9e5e  4k UltraHD Фотограф и Видеооператор

        item_rating_reviews_count  item_rating            item_price  \
146790                      152.0     4.980263  1000.000000000000000
192095                      152.0     4.980263  1000.000000000000000

        item_microcat_id      item_longitude  item_location_id  \
146790           2301874  73.374724999999998            642320
192095           2301874  73.374724999999998            642320

             item_latitude  item_is_phone_hidden  item_is_message_forbidden  \
146790  54.984661000000003                 False                      False
192095  54.984661000000003                 False                      False

                                    item_infm_params_text  \
146790  Вид услуги Фото- и видеосъёмка Место оказания ...
192095  Вид услуги Фото- и видеосъёмка Место оказания ...

                                     item_description_raw  item_category_id
146790  Если что-то срочное, звоните хоть в 4 ночи! \n...               114
192095  Если что-то срочное, звоните хоть в 4 ночи! \n...               114
---
       search_query           item_id          item_title_raw  \
80673     видеограф  1196799c445be766  Видеограф. Видеосъемка
144713    видеограф  1196799c445be766  Видеограф. Видеосъемка

        item_rating_reviews_count  item_rating            item_price  \
80673                        85.0     4.952941  5000.000000000000000
144713                       85.0     4.952941  5000.000000000000000

        item_microcat_id      item_longitude  item_location_id  \
80673            2301875  49.146729999999998            650400
144713           2301875  49.146729999999998            650400

             item_latitude  item_is_phone_hidden  item_is_message_forbidden  \
80673   55.821148000000001                 False                      False
144713  55.821148000000001                 False                      False

                                    item_infm_params_text  \
80673   Вид услуги Фото- и видеосъёмка Место оказания ...
144713  Вид услуги Фото- и видеосъёмка Место оказания ...

                                     item_description_raw  item_category_id
80673   Если вам нужна продакшн-студия, которая делает...               114
144713  Если вам нужна продакшн-студия, которая делает...               114
---
       search_query           item_id        item_title_raw  \
268826    видеограф  4c72f0ad6523ca64  Свадебный рилсмейкер
358571    видеограф  4c72f0ad6523ca64  Свадебный рилсмейкер

        item_rating_reviews_count  item_rating            item_price  \
268826                        9.0          5.0  2800.000000000000000
358571                        9.0          5.0  2800.000000000000000

        item_microcat_id      item_longitude  item_location_id  \
268826           2301875  30.468228577999298            653240
358571           2301875  30.468228577999298            653240

             item_latitude  item_is_phone_hidden  item_is_message_forbidden  \
268826  59.919175440839062                  True                      False
358571  59.919175440839062                  True                      False

                                    item_infm_params_text  \
268826  Вид услуги Фото- и видеосъёмка Место оказания ...
358571  Вид услуги Фото- и видеосъёмка Место оказания ...

                                     item_description_raw  item_category_id
268826  Идeт бронь дат на лето 2026 гoд, успeвайте заб...               114
358571  Идeт бронь дат на лето 2026 гoд, успeвайте заб...               114
---

Одно объявление может выбираться по очень многим запросам — вот самое популярное:

In [ ]:
train[train["item_id"]=="391037f10a20ee24"]

,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category,item_title_raw,item_rating_reviews_count,item_rating,item_price,item_microcat_id,item_longitude,item_location_id,item_latitude,item_is_phone_hidden,item_is_message_forbidden,item_infm_params_text,item_id,item_description_raw,item_category_id
4930,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
5533,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
5996,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
9407,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
13660,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480687,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
482630,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
491646,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
493492,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114
494582,увеличение губ,653240,0,"Тип услуги Косметология Вид услуги Красота, зд...",114,"Увеличение губ,Фулл Фэйс,м.Комендантский и Озерки",123.0,4.934959,6990.000000000000000,2096640,30.318330992856225,653240,60.041219693112787,False,False,"Вид услуги Красота, здоровье Место оказания ус...",391037f10a20ee24,Описание\n❗️6900 за 1 мл❗️Цeнa без дoплат‼️Oпы...,114

## Категория

В бенчмарке `search_category` почти всегда 114, у 222 запросов — 0. Как сигнал для выбора объявлений категория почти ничего не даёт

In [ ]:
queries["search_category"].value_counts()

114    2230
0       222
Name: search_category, dtype: int64

## Фильтры запроса

`search_infm_params_text` — выбранные пользователем фильтры, например «Вид услуги Ремонт и отделка». Бывают запросы, где заполнено только название фильтра без значения.

In [ ]:
queries[queries["search_infm_params_text"]=="Вид услуги"]

,query_id,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category
111,NjWdw4HSKj2LmpYH,экскурсии лазаревское,633655,0,Вид услуги,114
117,jhqvJdOYB0SP0KqJ,скупка фотоаппаратов,107621,0,Вид услуги,114
215,SVFfhQTJ5W0IOJtK,теплая беседка,634930,0,Вид услуги,114
298,Rv9yM596h15myHBU,авто разбор,645530,0,Вид услуги,114
484,8pmTLkEsss3S0BUq,надпись на футболке печать,637640,0,Вид услуги,114
540,VLa9UWTGQaGOXQYR,от шершней,646600,0,Вид услуги,114
577,hXCl0sxTmJFpVz0u,футболки с принтами на заказ,637640,0,Вид услуги,114
609,0mtMahErLgwnbCRg,отравление тараканов,661950,0,Вид услуги,114
628,3Ck0jwB6hlydPX2V,студия для фотосессии,637640,0,Вид услуги,114
648,no5QcEFwHNu79q7v,стоматолог,642320,0,Вид услуги,114
661,MwihntuNwLkGlNUi,визитки реклама,642320,0,Вид услуги,114
705,V5AjC1z3YHHY9sr2,crypto card,107620,0,Вид услуги,114
712,9XvO3wY800LCdjTS,услуги психолога оторвать от алкоголя,650400,0,Вид услуги,114
724,ujQDSd0cNAUT2r9a,стенд,625390,0,Вид услуги,114
738,atN2opGb4JaKny3Q,лофт пространство с проектором,654070,0,Вид услуги,114
770,oq3fJUfX1kucWSIo,консультация психолога,659300,0,Вид услуги,114
781,cLEo318Z3t4yZOBI,печать подарочных сертификатов,640860,0,Вид услуги,114
829,IjrzlEzxVhWvPNib,выкуп комплектующих пк,624840,0,Вид услуги,114
861,vri0MxSsM58W7tvu,собрать велосипед новый,653240,0,Вид услуги,114
865,i1ylf0PscFzSdEAK,виза шенген,107621,0,Вид услуги,114
869,35IRmV9hWdV13DrC,травля крыс,107620,0,Вид услуги,114
874,0hSN651avx2MF37v,поморить тараканов,653040,0,Вид услуги,114
923,pHI2WilenhE99aUR,информационный стенд,654070,0,Вид услуги,114
971,oEGIpK4sOKslghXD,uv dtf наклейки,637640,0,Вид услуги,114
1041,TfdlJ1kjjbJfoqNp,изготовление стендов,635320,0,Вид услуги,114
1067,IASoqsDKQ7YLil8q,скупка роботов пылесосов,661460,0,Вид услуги,114
1148,TRUYoYvCwv5lBOi3,сделать печать для ип,652000,0,Вид услуги,114
1166,Gw04fpNzQ1xeO0gJ,развод мостов на катере,653240,0,Вид услуги,114
1187,zSNkitAHBfK6BSxn,обработка стен от плесени,661420,0,Вид услуги,114
1218,aiNvLOx6SlRpHlhT,печать на пластике,650510,0,Вид услуги,114
1233,W5m8Qplv08i3dHNO,сделать печать для ип лененский район,656350,0,Вид услуги,114
1259,yPrM9knzFG7wbtmD,термотрансферная печать,642790,0,Вид услуги,114
1260,cnESUqOrs9JGPlaP,выкуп проблемных авто,624770,0,Вид услуги,114
1267,TLeCy1r1EPMZ6O7k,уничтожение ос,633540,0,Вид услуги,114
1274,wFVfwcSHXwIqu28R,йога на голове,650510,0,Вид услуги,114
1286,xsmQ9y05eoZQnYqc,изготовление наклеек на авто,637680,0,Вид услуги,114
1303,HPFjrSI0AJkMDRqU,байер из казахстана,637640,0,Вид услуги,114
1430,DnczTygdRiRkhpIv,байер голландия,621540,0,Вид услуги,114
1546,BGdcFIbENgBxrNin,изготовление наклеек на автомобили,107621,0,Вид услуги,114
1560,MKM41eLm0AcmG70x,онлайн занятия в зале,637770,0,Вид услуги,114
1575,KcUApvvArgncpVqF,домик на двоих с чаном,107620,0,Вид услуги,114
1660,8VLMxreO7HynO7j1,подолог красноармейский,624840,0,Вид услуги,114
1686,Pdl3iIJVLSkfEQsH,баер китай,653240,0,Вид услуги,114
1696,9t4OItMgGwHVH0i7,фотостудия в аренду на свадьбу,640860,0,Вид услуги,114
1775,hueDwu4c2W4deBjm,беседка для мероприятия,661420,0,Вид услуги,114
1848,J5W6EEhVhZll9PH3,световой короб вывеска,107620,0,Вид услуги,114
1880,gT2STwAIpgF51PWN,против тараканов,657600,0,Вид услуги,114
1945,Mz8pjZqmTgYqE9Fo,промоутер раздача листовок,637640,0,Вид услуги,114
1979,1vLMj2GQWeRVi8LH,иин казахстана,637640,0,Вид услуги,114
2036,rbP9kQbyIuQNrrUM,ремонт велосипедов шоссейные,637640,0,Вид услуги,114
2140,7C7EOYTRdcOXnGNO,карта для оплаты зарубежом,634450,0,Вид услуги,114
2191,OwySGTKNFCAyswzi,печать на банере,654070,0,Вид услуги,114
2199,FzujL8Tvr7cbSNMp,печать на бумаге,628500,0,Вид услуги,114
2205,9xVZPQZBbpMYOhGd,регрессолог медиум,656901,0,Вид услуги,114
2253,LxGxvoIczTaN5d1n,печать наклеек и стикеров,653040,0,Вид услуги,114
2289,7MfSjtoQ2Qm9XBGz,отдых с бассейном,633540,0,Вид услуги,114
2305,Kn8TUA6bU0KAQd2Y,нарколог,639530,0,Вид услуги,114
2318,LfdcaUDNV7dzF1Tp,психолог эжва,648630,0,Вид услуги,114
2414,FWKjIqHexWpafVVL,скупка музыкальных инструментов,653240,0,Вид услуги,114
2451,lMQlWhgC1WeP0QFa,реклама банер,637440,0,Вид услуги,114

In [ ]:
train[train["search_infm_params_text"]=="Вид услуги"]

,search_query,search_location_id,search_is_delivery_search,search_infm_params_text,search_category,item_title_raw,item_rating_reviews_count,item_rating,item_price,item_microcat_id,item_longitude,item_location_id,item_latitude,item_is_phone_hidden,item_is_message_forbidden,item_infm_params_text,item_id,item_description_raw,item_category_id
8,выкуп компьютеров,661420,0,Вид услуги,114,"Выкуп пк, ноутбуков,приставок",1071.0,4.984127,100000.000000000000000,2303374,61.308090000000000,661420,55.174182999999999,False,False,Вид услуги Место оказания услуг ул. Братьев Ка...,1806b31ef88a665f,"Срoчный Выкуп Bидeокарт,Ноутбуков,Mайнинг фeрм...",114
27,выкуп авто,650520,0,Вид услуги,114,Выкуп авто,6.0,5.000000,-1.000000000000000,2303374,51.809113000000004,650520,55.634070999999999,False,False,Вид услуги Место оказания услуг пр-т Химиков Т...,c74b4bb618a08ecc,7/24 срочно выкуп авто в любом состоянии! биты...,114
28,неоновая вывеска,633080,0,Вид услуги,114,Неоновая вывеска. Хит продаж,115.0,4.913043,650.000000000000000,2302479,38.077114999999999,633080,44.561011999999998,True,False,Вид услуги Место оказания услуг Краснодарский ...,5bb11051b1e108d0,⚡ Неоновые вывески от NEON PREMIUM!\n\n🧑‍💻 Нап...,114
150,изготовление печатей,623760,0,Вид услуги,114,Печати и штампы без документов,183.0,4.994536,300.000000000000000,2302479,37.833230999999998,623760,51.297974000000004,True,False,Вид услуги Место оказания услуг Белгородская о...,9828d1720d7e1b79,"Изготавливаем Печати и штампы по оттиску , от ...",114
253,выкуп авто,656901,0,Вид услуги,114,Выкуп авто сегодня - Без торга,56.0,5.000000,55555555.000000000000000,2303374,35.917474644180274,656901,56.857100231431772,False,False,"Вид услуги Место оказания услуг Тверь, улица А...",b0805d4de1a3e432,"🚗 Хотите продать автомобиль быстро, без размещ...",114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497423,печать баннеров,654070,0,Вид услуги,114,"Екатеринбург. Печать,монтаж рекламы;баннеры,пл...",19.0,5.000000,-1.000000000000000,2302479,60.668136599999997,654070,56.746608729999998,False,False,Вид услуги Место оказания услуг Свердловская о...,cc1a2f72c0a5b8f6,Мы рекламное агентство Image Media работаем с ...,114
497449,срочный выкуп авто,621590,0,Вид услуги,114,Выкуп автомобилей в любом состояние,103.0,4.815534,-1.000000000000000,2303374,83.774383540000002,621630,53.364456179999998,False,False,Вид услуги Место оказания услуг Алтайский край...,2e351d728c5b106a,Срочный выкуп автомобилей\nНужна быстрая прода...,114
497489,тараканы,631870,0,Вид услуги,114,"Дезинсекция тараканов, уничтожение клопов, блох",79.0,4.962025,330.000000000000000,2301738,49.644658000000000,631870,58.588833000000001,False,False,Вид услуги Место оказания услуг Кировская обл....,46249342e2345667,🪳 Дезинсекция от насекомых и грызунов — профес...,114
497499,копицентр,625810,0,Вид услуги,114,"Наружная реклама, вывески, объемные буквы, неон",66.0,5.000000,555.000000000000000,2302479,39.200296000000002,625810,51.660781000000000,False,False,Вид услуги Место оказания услуг Воронежская об...,7bbcffdfe896eceb,"СДЕЛАЕМ ВЫВЕСКУ ЯРЧЕ И КРАСИВЕЕ, ЧЕМ У ВАШИХ К...",114
497582,вывеска,643560,0,Вид услуги,114,"Рекламные вывески, Световые короба, Баннеры",6.0,5.000000,1000.000000000000000,2302479,45.017426999999998,643560,53.170634000000000,False,False,"Вид услуги Место оказания услуг Пенза, улица С...",298eaac11a29b694,"Изготoвлeниe нaружной рекламы любой слoжноcти,...",114

## Локация

Один и тот же текст ищут в сотнях городов: «маникюр» встречается в 633 локациях.

In [ ]:
train[train["search_query"]=="маникюр"]["item_location_id"].value_counts()

item_location_id
637640    507
653240    501
654070    130
650400    127
641780    121
         ...
625720      1
629210      1
656930      1
656820      1
659940      1
Name: count, Length: 633, dtype: int64

Внутри одной локации выбор тоже неравномерный: несколько объявлений собирают заметную долю кликов.

In [ ]:
train[train["item_location_id"] == 652430]["item_id"].value_counts()

dc090a318115e720    18
142f24a97b5713a9    17
a7ea0a63cbc5be25    12
719f4fb8c18882f5    12
a90e51853233190d    12
                    ..
b453ca184ad48f89     1
0b9e9ff7b812dcb2     1
f2e7cc87c0dcb62c     1
82b25cc859d495f5     1
9759974b0c26af4d     1
Name: item_id, Length: 2248, dtype: int64

История есть не для всех запросов: например, по «нарколог» в train нет ни одной строки.

In [ ]:
train[train["search_query"]=="нарколог"]

Empty DataFrame
Columns: [search_query, search_location_id, search_is_delivery_search, search_infm_params_text, search_category, item_title_raw, item_rating_reviews_count, item_rating, item_price, item_microcat_id, item_longitude, item_location_id, item_latitude, item_is_phone_hidden, item_is_message_forbidden, item_infm_params_text, item_id, item_description_raw, item_category_id]
Index: []

## Выводы

- Запрос — полная комбинация полей `search_*`: один текст в разных локациях и с разными фильтрами даёт разные наборы объявлений.
- Объявления train и бенчмарка почти не пересекаются, поэтому поиск должен работать по содержанию.
- Полные дубли строк — повторные клики, перед валидацией их удаляю.
- Цена и координаты требуют приведения типов.
- Локация выглядит сильным сигналом, её вклад проверяю в `02_experiments`.